name: Build Push frontend to Docker Hub

on:
  push:
    paths:
      - packages/frontend/**
      - packages/common/**
      - package*.json
      - "!.github/**"
      - ".github/workflows/build-push-frontend.yaml"
    branches:
      - main

env:
  NEXT_PUBLIC_API_SERVER_URL: https://radioter.io/api-v2
  NEXT_PUBLIC_PLAYBACK_SERVER_URL: https://radioter.io/pb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILD=${{ github.sha }}
          file: packages/frontend/Dockerfile
          context: .
          push: true
          tags: |
            pldin601/radioterio-frontend:latest,
            pldin601/radioterio-frontend:${{ github.sha }}
